version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: .git/

jobs:
  my-job:
    executor: my-executor
    steps:
      - checkout
      - run:
        name: ls
        command: |
          ls -al
